In [2]:
import numpy as np
import sys

## Comparing Numpy Array and Python List

In [3]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [4]:
array=np.arange(1000)
print(array.size*array.itemsize)

4000


In [5]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

### N Dimensional Arrays

In [10]:
a=np.array([[1,2],[2,3],[4,5]])
a.ndim

2

In [9]:
a.itemsize

4

In [11]:
a.dtype

dtype('int32')

In [14]:
a=np.array([[1,2],[2,3],[4,5]],dtype=np.float64)
a.dtype

dtype('float64')

In [15]:
a.size

6

In [16]:
a.shape

(3, 2)

In [17]:
a

array([[ 1.,  2.],
       [ 2.,  3.],
       [ 4.,  5.]])

In [18]:
np.zeros((4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.ones((4,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
np.arange(1,7,2)

array([1, 3, 5])

In [21]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [22]:
a.reshape(2,3)

array([[ 1.,  2.,  2.],
       [ 3.,  4.,  5.]])

In [23]:
a.ravel()

array([ 1.,  2.,  2.,  3.,  4.,  5.])

In [24]:
a

array([[ 1.,  2.],
       [ 2.,  3.],
       [ 4.,  5.]])

In [26]:
a.min()


1.0

In [27]:
a.max()

5.0

In [28]:
a.sum(axis=0)

array([  7.,  10.])

In [29]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.41421356,  1.73205081],
       [ 2.        ,  2.23606798]])

In [30]:
np.std(a)

1.3437096247164249